name: flutter_tools
description: Some Flutter tools that I frequently use.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  flutter_svg: ^1.0.0
  url_launcher: ^6.0.12
  cached_network_image: ^3.2.0
  image_picker: ^0.8.5+3
  image_cropper: ^1.5.0
  flutter_screenutil: ^5.1.0
  package_info: ^2.0.2
  device_info: ^2.0.3
  permission_handler: ^10.2.0
  pull_to_refresh: 2.0.0
  event_bus: ^2.0.0
  json_annotation: ^4.6.0
  flutter_riverpod: ^2.1.1
  flutter_smart_dialog: ^4.7.1
  html: ^0.15.0
  lottie: ^2.0.0
  # 微信分享
  fluwx_no_pay: 3.13.1
  # 个推：https://github.com/GetuiLaboratory/getui-flutter-plugin
  getuiflut: ^0.2.18
  r_dart_library:
    git:
      url: 'https://github.com/YK-Unit/r_dart_library.git'
      ref: 0.4.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/ic_back_black.png
  - assets/images/icon_input_paste_normal.svg
  - assets/images/icon_links_clear.svg
  - assets/lottie/loading.json
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - assets
  fonts:
  - assets/fonts
